version: '3'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db
      - DB_USER=cardicom_user
      - DB_PASSWORD=cardicom_pass
      - DB_NAME=cardicom
    depends_on:
      - composer
      - db

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=cardicom
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=cardicom_user
      - MYSQL_PASSWORD=cardicom_pass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./u543420.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  composer:
    image: composer:latest
    volumes:
      - .:/app
    command: install --ignore-platform-reqs --no-scripts

volumes:
  mysql_data: 